import type { BrochuresParams } from '@avenir/core';

export const defaultBrochuresParams: BrochuresParams = {
  machines_impression: [
    {
      id: 'hp_indigo',
      nom: 'HP Indigo (numérique)',
      techno: 'numerique',
      format_max_mm: { largeur: 330, hauteur: 488 },
      vitesse_feuilles_h: 4000,
      taux_horaire_ht: 60,
      cout_calage_ht: 0,
      recto_verso_calage_unique: true,
      gaches_pct: 3,
      operateur_taux_horaire_ht: 30,
      actif: true,
    },
    {
      id: 'speedmaster',
      nom: 'Speedmaster (offset)',
      techno: 'offset',
      format_max_mm: { largeur: 520, hauteur: 740 },
      vitesse_feuilles_h: 12000,
      taux_horaire_ht: 120,
      cout_calage_ht: 50,
      recto_verso_calage_unique: true,
      gaches_pct: 8,
      operateur_taux_horaire_ht: 35,
      actif: true,
    },
  ],
  machines_faconnage: [
    {
      id: 'agrafeuse',
      nom: 'Agrafeuse',
      type: 'agrafe',
      vitesse_h: 1500,
      taux_horaire_ht: 40,
      operateur_taux_horaire_ht: 30,
      cout_consommables_unitaire_ht: 0.01,
    },
    {
      id: 'dos_carre_machine',
      nom: 'Machine dos carré collé',
      type: 'dos_carre_colle',
      vitesse_h: 800,
      taux_horaire_ht: 60,
      operateur_taux_horaire_ht: 30,
      cout_consommables_unitaire_ht: 0.05,
    },
    {
      id: 'spirale_machine',
      nom: 'Spiraleuse',
      type: 'spirale',
      vitesse_h: 600,
      taux_horaire_ht: 50,
      operateur_taux_horaire_ht: 30,
      cout_consommables_unitaire_ht: 0.2,
    },
    {
      id: 'wire_o_machine',
      nom: 'Wire-O',
      type: 'wire_o',
      vitesse_h: 500,
      taux_horaire_ht: 50,
      operateur_taux_horaire_ht: 30,
      cout_consommables_unitaire_ht: 0.25,
    },
    {
      id: 'plieuse',
      nom: 'Plieuse',
      type: 'plieuse',
      vitesse_h: 5000,
      taux_horaire_ht: 30,
      operateur_taux_horaire_ht: 25,
      cout_consommables_unitaire_ht: 0,
    },
  ],
  reliures: [
    {
      id: 'agrafe_std',
      nom: 'Agrafé piqûre cheval',
      type: 'agrafe',
      pages_multiple: 4,
      pages_min: 8,
      pages_max: 64,
      machine_faconnage_id: 'agrafeuse',
      sous_traite: false,
    },
    {
      id: 'dos_colle_std',
      nom: 'Dos carré collé',
      type: 'dos_carre_colle',
      pages_multiple: 2,
      pages_min: 32,
      pages_max: 300,
      machine_faconnage_id: 'dos_carre_machine',
      sous_traite: false,
    },
    {
      id: 'dos_cousu_st',
      nom: 'Dos carré cousu (sous-traitance)',
      type: 'dos_carre_cousu',
      pages_multiple: 4,
      pages_min: 80,
      pages_max: 500,
      machine_faconnage_id: 'dos_carre_machine',
      sous_traite: true,
      cout_fournisseur_brochure_ht: 1.5,
      marge_sous_traitance_pct: 30,
    },
    {
      id: 'spirale_std',
      nom: 'Spirale plastique',
      type: 'spirale',
      pages_multiple: 1,
      pages_min: 8,
      pages_max: 300,
      machine_faconnage_id: 'spirale_machine',
      sous_traite: false,
    },
    {
      id: 'wire_o_std',
      nom: 'Wire-O',
      type: 'wire_o',
      pages_multiple: 1,
      pages_min: 8,
      pages_max: 300,
      machine_faconnage_id: 'wire_o_machine',
      sous_traite: false,
    },
  ],
  papiers: [
    {
      id: 'couche_135',
      nom: 'Couché 135g (intérieur)',
      grammage: 135,
      formats_achat: [
        { largeur_mm: 320, hauteur_mm: 450, prix_paquet_ht: 60, feuilles_par_paquet: 500 },
        { largeur_mm: 520, hauteur_mm: 720, prix_paquet_ht: 140, feuilles_par_paquet: 500 },
      ],
      compatible_techno: ['offset', 'numerique'],
    },
    {
      id: 'couche_170',
      nom: 'Couché 170g (intérieur épais)',
      grammage: 170,
      formats_achat: [
        { largeur_mm: 320, hauteur_mm: 450, prix_paquet_ht: 75, feuilles_par_paquet: 500 },
      ],
      compatible_techno: ['offset', 'numerique'],
    },
    {
      id: 'couverture_300',
      nom: 'Couverture 300g',
      grammage: 300,
      formats_achat: [
        { largeur_mm: 320, hauteur_mm: 450, prix_paquet_ht: 90, feuilles_par_paquet: 250 },
      ],
      compatible_techno: ['offset', 'numerique'],
    },
    {
      id: 'recycle_350',
      nom: 'Recyclé 350g (couverture, numérique uniquement)',
      grammage: 350,
      formats_achat: [
        { largeur_mm: 320, hauteur_mm: 450, prix_paquet_ht: 120, feuilles_par_paquet: 250 },
      ],
      compatible_techno: ['numerique'],
    },
  ],
  formats_standards: [
    { id: 'A6', largeur_mm: 105, hauteur_mm: 148 },
    { id: 'A5', largeur_mm: 148, hauteur_mm: 210 },
    { id: 'A4', largeur_mm: 210, hauteur_mm: 297 },
    { id: 'A6_paysage', largeur_mm: 148, hauteur_mm: 105 },
    { id: 'A5_paysage', largeur_mm: 210, hauteur_mm: 148 },
    { id: 'A4_paysage', largeur_mm: 297, hauteur_mm: 210 },
    { id: 'A6_carre', largeur_mm: 148, hauteur_mm: 148 },
    { id: 'A5_carre', largeur_mm: 210, hauteur_mm: 210 },
    { id: 'A4_carre', largeur_mm: 297, hauteur_mm: 297 },
  ],
  finitions: [
    {
      id: 'pelliculage_brillant',
      nom: 'Pelliculage brillant (couverture)',
      type: 'par_face',
      prix_ht: 5,
      sous_traite: false,
    },
    {
      id: 'pelliculage_mat',
      nom: 'Pelliculage mat (couverture)',
      type: 'par_face',
      prix_ht: 6,
      sous_traite: false,
    },
    {
      id: 'gaufrage',
      nom: 'Gaufrage couverture (unitaire)',
      type: 'unitaire',
      prix_ht: 0.5,
      sous_traite: false,
    },
    {
      id: 'dorure_st',
      nom: 'Dorure à chaud (sous-traitance, forfait)',
      type: 'forfait',
      prix_ht: 0,
      sous_traite: true,
      cout_fournisseur_ht: 200,
      marge_sous_traitance_pct: 40,
    },
  ],
  seuil_offset_quantite_min: 500,
  seuil_pages_pliage: 8,
  machine_pliage_id: 'plieuse',
  frais_fixes_ht: 50,
  bat_prix_ht: 30,
  marge_pct_offset: 60,
  marge_pct_numerique: 50,
  tva_pct: 20,
  degressif: [
    { seuil: 500, remise_pct: 5 },
    { seuil: 2000, remise_pct: 10 },
    { seuil: 10000, remise_pct: 20 },
  ],
};
