import type { FlyersParams } from '@avenir/core';

export const defaultFlyersParams: FlyersParams = {
  machines: [
    {
      id: 'hp_indigo',
      nom: 'HP Indigo (numérique)',
      techno: 'numerique',
      format_max_mm: { largeur: 330, hauteur: 488 },
      vitesse_feuilles_h: 1500,
      taux_horaire_ht: 60,
      cout_calage_ht: 0,
      recto_verso_calage_unique: true,
      gaches_pct: 2,
      operateur_taux_horaire_ht: 30,
      actif: true,
    },
    {
      id: 'speedmaster',
      nom: 'Speedmaster (offset)',
      techno: 'offset',
      format_max_mm: { largeur: 720, hauteur: 1020 },
      vitesse_feuilles_h: 12000,
      taux_horaire_ht: 80,
      cout_calage_ht: 40,
      recto_verso_calage_unique: true,
      gaches_pct: 5,
      operateur_taux_horaire_ht: 35,
      actif: true,
    },
  ],
  papiers: [
    {
      id: 'couche_brillant_135',
      nom: 'Couché brillant 135g',
      grammage: 135,
      formats_achat: [
        { largeur_mm: 320, hauteur_mm: 464, prix_paquet_ht: 21, feuilles_par_paquet: 500 },
        { largeur_mm: 720, hauteur_mm: 1020, prix_paquet_ht: 90, feuilles_par_paquet: 250 },
      ],
      compatible_techno: ['numerique', 'offset'],
    },
    {
      id: 'couche_mat_170',
      nom: 'Couché mat 170g',
      grammage: 170,
      formats_achat: [
        { largeur_mm: 320, hauteur_mm: 464, prix_paquet_ht: 28, feuilles_par_paquet: 500 },
        { largeur_mm: 720, hauteur_mm: 1020, prix_paquet_ht: 110, feuilles_par_paquet: 250 },
      ],
      compatible_techno: ['numerique', 'offset'],
    },
    {
      id: 'recycle_350',
      nom: 'Recyclé 350g (numérique uniquement)',
      grammage: 350,
      formats_achat: [
        { largeur_mm: 320, hauteur_mm: 464, prix_paquet_ht: 60, feuilles_par_paquet: 250 },
      ],
      compatible_techno: ['numerique'],
    },
  ],
  formats_standards: [
    { id: 'A6', largeur_mm: 105, hauteur_mm: 148 },
    { id: 'A5', largeur_mm: 148, hauteur_mm: 210 },
    { id: 'A4', largeur_mm: 210, hauteur_mm: 297 },
    { id: 'A3', largeur_mm: 297, hauteur_mm: 420 },
    { id: 'DL', largeur_mm: 99, hauteur_mm: 210 },
    { id: 'CV', largeur_mm: 85, hauteur_mm: 55 },
  ],
  finitions: [
    {
      id: 'pelliculage_brillant',
      nom: 'Pelliculage brillant',
      type: 'par_face',
      prix_ht: 5,
      sous_traite: false,
    },
    {
      id: 'pelliculage_mat',
      nom: 'Pelliculage mat',
      type: 'par_face',
      prix_ht: 6,
      sous_traite: false,
    },
    {
      id: 'vernis_uv',
      nom: 'Vernis UV sélectif',
      type: 'm2',
      prix_ht: 12,
      sous_traite: false,
    },
    {
      id: 'coins_ronds',
      nom: 'Coins ronds',
      type: 'unitaire',
      prix_ht: 0.05,
      sous_traite: false,
    },
    {
      id: 'soft_touch',
      nom: 'Soft-touch (sous-traité)',
      type: 'forfait',
      prix_ht: 0,
      sous_traite: true,
      cout_fournisseur_ht: 80,
      marge_sous_traitance_pct: 30,
    },
  ],
  seuil_offset_quantite_min: 500,
  frais_fixes_ht: 25,
  bat_prix_ht: 30,
  marge_pct_offset: 40,
  marge_pct_numerique: 60,
  tva_pct: 20,
  degressif: [
    { seuil: 500, remise_pct: 5 },
    { seuil: 1000, remise_pct: 10 },
    { seuil: 5000, remise_pct: 15 },
  ],
};
